---
android_sdk_home: "{{ ANDROID_HOME|default('/opt/android-sdk-linux') }}"
android_sdk_volume_capacity: "{{ ANDROID_SDK_VOLUME_SIZE|default('10Gi') }}"
android_slave_image: "docker.io/aerogear/digger-android-slave-image:1.0.0-alpha"
android_slave_image_pull: true
android_slave_instance_cap: 3
android_slave_idle_minutes: 3
android_slave_resource_cpu_request: "{{ ANDROID_SLAVE_CPU_REQUEST|default('500m') }}"
android_slave_resource_cpu_limit: "{{ ANDROID_SLAVE_CPU_LIMIT|default('2000m') }}"
android_slave_resource_memory_request: "{{ ANDROID_SLAVE_MEMORY_REQUEST|default('500Mi') }}"
android_slave_resource_memory_limit: "{{ ANDROID_SLAVE_MEMORY_LIMIT|default('3000Mi') }}"

java_sdk_home: "{{ JAVA_HOME|default('/etc/alternatives/java_sdk_1.8.0') }}"

jenkins_master_memory_limit: 3Gi
jenkins_master_volume_capacity: "{{ JENKINS_VOLUME_SIZE|default('40Gi') }}"
