- name: delete AG-Digger resoures
  command: oc delete {{ item }} android-sdk
  with_items:
    - dc

- name: delete AG-Digger secret
  command: oc delete {{ item }} aerogear-digger
  with_items:
    - secret

- name: delete AG-Digger configmaps
  command: oc delete configmap {{ item }}
  with_items:
    - android
    - android-proxy
