- name: Create Mobile CI/CD secret file
  template:
    src: aerogear-digger.secret.yaml.j2
    dest: /tmp/aerogear-digger.secret.yaml
    force: true
  vars:
    statusMessage: "{{ status_message }}"
    statusPercentage: "{{ status_percentage }}"
    jenkinsUri: "{{ jenkins_uri }}"
    jenkinsPreexists: "{{ jenkins_preexists }}"

- name: Create Mobile CI/CD secret
  command: "oc replace -f /tmp/aerogear-digger.secret.yaml -n {{ namespace }}"
