---
- name: buildfarm-apb playbook to test the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - /opt/ansible/vars/main.yml
  - /opt/ansible/vars/test.yml
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  post_tasks:
  - name: Create project for namespace
    openshift_v1_project:
      name: '{{ namespace }}'
  - include_role: name=provision-buildfarm-apb
  - include_role: name=test-buildfarm-apb tasks_from=provision.yml
  - include_role: name=deprovision-buildfarm-apb
  - include_role: name=test-buildfarm-apb tasks_from=deprovision.yml